version: '3.9'

services:
  backend:
    build:
      context: backend
    restart: always
    networks:
      - bookhaven-network
    ports:
      - 8080:8080

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    networks:
      - bookhaven-network

networks:
  bookhaven-network:
    driver: bridge