spring:
  config:
    import: optional:secrets.yaml
  devtools:
    livereload:
      enabled: true
      port: 32729
  application:
    name: bookHaven
  datasource:
    url: ${DB_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  webflux:
    cors:
      enabled: true
  webmvc:
    cors:
      enabled: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}